Gemfile:
  optional:
    ':extra':
      - gem: 'net-ldap'
        version: '~> 0.12.1'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
.rubocop.yml:
  cops:
    Security/MarshalLoad: false
