---
Gemfile:
  optional:
    ':extra':
      - gem: 'net-ldap'
        version: '~> 0.18.0'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
.github/workflows/ci.yml:
    unmanaged: true
