Gemfile:
  optional:
    ':extra':
      - gem: 'net-ldap'
        version: '~> 0.16.1'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
.rubocop.yml:
  cops:
    Security/MarshalLoad: false
.travis.yml:
  secure: "rIqlHIjLtJOQiJ5LX8qPje8PFBcu52Vv5GEpioxp+jf7/BQVGkMik1bVIkkorI5CDsmjJJqfZwuuMK3JoHKnlI8jNtSQlA/lrszRJm2fhCBXZAQwQz2n8azaszH/ysNsBJ56zZj/DlT+S7uR9gVLYiuHsTjgCLDQEfc1Y0yn6UbU04sGIuXmwCqF+E7vtGVyJW+PsdqakQawbb/jK8F0ah9cw3yj4CTQpMVIP/JwYubZ+ACXvrxWh8+/U8T7s8GE0+X8gcGRK1DB06iov09Mo78gHwx4jaedwFz/HUKyKZqfSqYNC4OA2/fPJsPOdje74Fb/IvDPLamEkgLcltjZsjdyq2mRlLej2WKhQb5wCEKFPDJAi18GcVOyayp9YDF0F6q1EfUhfJlJUj3eUJVO62dNujcFb6GM401qnWr3QD07V2PaHVQjGIO+FUykV+8s6x7qeBNxXQ2IBh1+n7iYBbIzibvMI3E0pLEThToWp+bheqHgjLSqZ6n/kttzPuBQHZCEgX2hAHH1g8IkEDgAYzV1exdqaICgCoj0IAnqhAOVDV1g9IZpxPc3UlP2oTLaY47W64F6sIKbBo/f7+wimnt/9bagzFI7uED+cOCF1IFglCQkl21kzTcrTIdztTyVkNicJtII/fKNuMKlZu4B5WATb+eZrFiiyyA09fwh+XU="
